path = "sample.toml"

[[rows]]
Name = "Bob"
Age = "42"
Occupation = "Master"

[[rows]]
Name = "Flex"
Age = "44.5"
Occupation = "Student"

[[rows]]
Name = "Boba"
Age = "42"
Occupation = "Master"

[[rows]]
Name = "Flex"
Age = "44.5"
Occupation = "Student"

[[rows]]
Name = "Bobe"
Age = "42"
Occupation = "Master"

[[rows]]
Name = "Heroku"
Age = "11"
Occupation = "Other"
