normal:
  q: Quit
  ctrl-c: Quit
  enter: EditCell
  r: AppendRow
  c: AppendColumn
  h: EditHeader
  f: EditFileName
  ctrl-s: Save
  ctrl-t: SaveToml
  ctrl-k: SaveKeyBindings
  right: SelectCellRight
  left: SelectCellLeft
  up: SelectCellUp
  down: SelectCellDown
  "?": ToggleKeyBindingsDisplay
edit:
  enter: ApplyEdit
  ctrl-enter: ConfirmSelectCellRight
  alt-enter: ConfirmSelectCellDown
  esc: CancelEdit
  tab: NextSuggestion
  down: NextSuggestion
  up: PreviousSuggestion
  shift-right: ConfirmSelectCellRight
  shift-left: ConfirmSelectCellLeft
  shift-up: ConfirmSelectCellRight
  shift-down: ConfirmSelectCellDown
  right: CursorRight
  left: CursorLeft
