normal:
  q: Quit
  ctrl-c: Quit
  enter: EditCell
  r: AppendRow
  alt-r: DeleteRow
  c: AppendColumn
  alt-c: DeleteColumn
  v: EditHeader
  f: EditFileName
  ctrl-s: Save
  ctrl-t: SaveToml
  ctrl-j: SaveJson
  ctrl-y: SaveYml
  ctrl-r: SaveRon
  ctrl-k: SaveKeyBindings
  right: SelectCellRight
  left: SelectCellLeft
  up: SelectCellUp
  down: SelectCellDown
  h: SelectCellLeft
  j: SelectCellDown
  k: SelectCellUp
  l: SelectCellRight
  alt-right: MoveColumnRight
  alt-left: MoveColumnLeft
  alt-up: MoveRowUp
  alt-down: MoveRowDown
  s: SortByColumn
  alt-s: SortByColumnReversed
  "?": ToggleKeyBindingsDisplay
edit:
  enter: ApplyEdit
  ctrl-enter: ConfirmSelectCellRight
  alt-enter: ConfirmSelectCellDown
  esc: CancelEdit
  tab: NextSuggestion
  down: NextSuggestion
  up: PreviousSuggestion
  shift-right: ConfirmSelectCellRight
  shift-left: ConfirmSelectCellLeft
  shift-up: ConfirmSelectCellRight
  shift-down: ConfirmSelectCellDown
  right: CursorRight
  left: CursorLeft
